    "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "  2%|█▌                                                                               | 10/503 [00:42<34:26,  4.19s/it]C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:46: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead\n",
      "  base_score = int(round(volatility * 10000))\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "  2%|█▊                                                                               | 11/503 [00:43<26:21,  3.22s/it]C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:46: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead\n",
      "  base_score = int(round(volatility * 10000))\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "  2%|█▉                                                                               | 12/503 [00:47<27:11,  3.32s/it]C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:46: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead\n",
      "  base_score = int(round(volatility * 10000))\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "  3%|██                                                                               | 13/503 [00:48<22:03,  2.70s/it]C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:46: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead\n",
      "  base_score = int(round(volatility * 10000))\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "  3%|██▎                                                                              | 14/503 [00:52<25:45,  3.16s/it]C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:46: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead\n",
      "  base_score = int(round(volatility * 10000))\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "  3%|██▍                                                                              | 15/503 [00:54<20:27,  2.52s/it]C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:46: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead\n",
      "  base_score = int(round(volatility * 10000))\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipykernel_19188\\4250997119.py:12: FutureWarning: YF.download() has changed argument auto_adjust default to True\n",
      "  df = yf.download(ticker, period=\"5d\", interval=\"60m\", progress=False)\n",
      "C:\\Users\\david\\AppData\\Local\\Temp\\ipyker